---
components:
  - name: max31855
    description: Driver for MAX31855 cold-junction compensated thermocouple-to-digital converter
    group: temperature
    groups: []
    code_owners: UncleRus
    depends:
      - driver
      - log
    thread_safe: yes
    targets:
      - name: esp32
      - name: esp32s2
      - name: esp32c3
    licenses:
      - name: BSD-3
    copyrights:
      - author:
          name: UncleRus
        year: 2022
